In [2]:
import numpy as np
import torch

In [3]:
#Data Initialization
data = [[1,2] , [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [4]:
data = np.array(data)
x_np = torch.from_numpy(data)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [5]:
x_ones = torch.ones_like(x_data)
print(x_ones)
x_random = torch.rand_like(x_data , dtype=torch.float)
print(f"Random Tensor:\n {x_random}\n")

tensor([[1, 1],
        [1, 1]])
Random Tensor:
 tensor([[0.3530, 0.6230],
        [0.5892, 0.9307]])



In [6]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"random tensor:\n{rand_tensor}\n")
print(f"ones tensor:\n{ones_tensor}\n")
print(f"zeros tensor:\n{zeros_tensor}\n")

random tensor:
tensor([[0.8548, 0.3835, 0.9384],
        [0.0610, 0.4567, 0.4667]])

ones tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [7]:
# Tensor Attributes
tensor = torch.rand(3,4)
print(f" tensor:\n{tensor}\n")
print(f" tensor_shape:\t{tensor.shape}\n")
print(f" tensor_type:\t{tensor.dtype}\n")
print(f" tensor_device:\t{tensor.device}\n")

 tensor:
tensor([[0.5265, 0.8133, 0.3753, 0.7698],
        [0.3475, 0.0139, 0.3594, 0.6352],
        [0.4509, 0.9027, 0.5610, 0.9757]])

 tensor_shape:	torch.Size([3, 4])

 tensor_type:	torch.float32

 tensor_device:	cpu



In [9]:
#Tensor Opertaions
#We move our tensor to the GPU if available
if torch.cuda.is_available():
   tensor = tensor.to('cuda') 
   print(f"tensor_device:\t{tensor.device}")


tensor_device:	cuda:0


In [24]:
tensor_1 = torch.rand(size=(2,2) , dtype=float)
tensor_2 = torch.rand(size=(2,2) , dtype=float)
tensor_3 = torch.cat([tensor_1 , tensor_2], dim=1)
print(tensor_3.shape)
print(tensor_1)
print(tensor_2)
print(tensor_3)

torch.Size([2, 4])
tensor([[0.4409, 0.2585],
        [0.8328, 0.2248]], dtype=torch.float64)
tensor([[0.0410, 0.4994],
        [0.6376, 0.7474]], dtype=torch.float64)
tensor([[0.4409, 0.2585, 0.0410, 0.4994],
        [0.8328, 0.2248, 0.6376, 0.7474]], dtype=torch.float64)


In [29]:
tensor_4 = tensor_1.mul(tensor_2) # element-wise product
print(tensor_4)
tensor_5 = tensor_1.mul(tensor_2.T)# matrix multiplication
print(tensor_5)

tensor([[0.0181, 0.1291],
        [0.5311, 0.1680]], dtype=torch.float64)
tensor([[0.0181, 0.1649],
        [0.4159, 0.1680]], dtype=torch.float64)


In [34]:
# Bridge with Numpy
t = torch.ones(2,2)
n = t.numpy()
t.add_(2)
print(f'torch:{t}\n')
print(f'numpy:{n}')

torch:tensor([[3., 3.],
        [3., 3.]])

numpy:[[3. 3.]
 [3. 3.]]
